autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  hosts:
    - host: acua.mpfglaser.nl
      paths:
        - path: /api/auth(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            servicePort: 3000
