version: '3.1'
services:
  locationdb:
    image: locationdb-e2e
    restart: always
    environment:
      POSTGRES_USER: locationdb
      POSTGRES_PASSWORD: locationdb
      DB_TO_CHECK: locationdb
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$DB_TO_CHECK']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  ticketdb:
    image: ticketdb-e2e
    restart: always
    environment:
      POSTGRES_USER: ticketdb
      POSTGRES_PASSWORD: ticketdb
      DB_TO_CHECK: ticketdb
    ports:
      - 5443:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$DB_TO_CHECK']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
