apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acua-ingress
  namespace: acua
  annotations:
    ingressClassName: "gce"
    kubernetes.io/ingress.global-static-ip-name: acua-static-ip
    networking.gke.io/managed-certificates: acua-certificate
    networking.gke.io/v1beta1.FrontendConfig: frontend-config
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: acua.mpfglaser.nl
      http:
        paths:
          - path: /api/location
            pathType: Prefix
            backend:
              service:
                name: location-service
                port:
                  number: 3000
          - path: /api/ticket
            pathType: Prefix
            backend:
              service:
                name: ticket-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acua
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: acua-certificate
  namespace: acua
spec:
  domains:
    - acua.mpfglaser.nl
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-config
  namespace: acua
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: FOUND
