apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acua-ingress
  namespace: acua
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: acua-static-ip
    networking.gke.io/managed-certificates: acua-certificate


spec:
  rules:
    - host: acua.mpfglaser.nl
      http:
        paths:
          # - path: /api/auth/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: auth-service
          #       port:
          #         number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acua
                port:
                  number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: acua-certificate
spec:
  domains:
    - acua.mpfglaser.nl
