apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acua-ingress
  namespace: acua
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  tls:
    - hosts:
      - acua.mpfglaser.nl
      - acua.test
  rules:
    - host: acua.test
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: acua
                port:
                  number: 8080
    - host: acua.mpfglaser.nl
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: acua
                port:
                  number: 8080

