name: 'Deploy'
on:
  workflow_run:
    workflows: ['CI'] # Replace "CI" with the name of your CI workflow
    types:
      - completed

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'staging' || startsWith(github.ref, 'refs/tags/release-') && 'production' || github.event_name == 'pull_request' && 'development' }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        service: ['acua', 'auth-service'] # Replace with your service names
    steps:
      - name: 'Checkout' # Checkout the repository code.
        uses: 'actions/checkout@v1'
      - name: 'Deploy ${{ matrix.service }}'
        uses: 'deliverybot/helm@master'
        with:
          token: '${{ github.token }}'
          secrets: '${{ toJSON(secrets) }}'
          chart: '${{ matrix.service }}'
          namespace: acua-${{ env.ENVIRONMENT }}
          release: ${{ matrix.service }}
          value-files: './helm/${{ matrix.service }}/${{ env.ENVIRONMENT }}-values.yml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
