name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  CI:
    env:
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set Shas'
        uses: nrwl/nx-set-shas@v3
      - name: 'Download Node Dependencies'
        run: npm ci
      - name: 'Formatting check'
        run: npx nx format:check
      - name: 'Run linting on affected projects'
        run: npx nx affected -t lint --parallel=3
      - name: 'Run tests on affected projects'
        run: npx nx affected -t test --parallel=3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build Docker images for affected projects'
        run: npx nx affected -t docker-build --parallel=3
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Set example secret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: acua
          secret-name: demo-k8s-secret
          data: lorem-ipsum
      # Deploy to Kubernetes
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.10.0
        with:
          action: deploy
          manifests: |
            kubernetes
